# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  host: 'localhost'
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'test_vive_development' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '12345' %>
test:
  <<: *default
  database: <%= ENV['DB_NAME'] ||  'test_vive_test' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '12345' %>
production:
  <<: *default
  database: <%= ENV['DB_PASSWORD_PROD'] || 'test_vive_production' %>
  username: <%= ENV['DB_USERNAME_PROD'] %>
  password: <%= ENV['DB_PASSWORD_PROD'] %>